create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default 'Reclaim member', company text, location text, avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.listings (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, title text not null, category text not null check (category in ('Lumber','Masonry','Fixtures','Hardware','Landscaping')), quantity text not null, price text not null default 'Free', location text not null, description text, image_url text, status text not null default 'active' check (status in ('active','sold','archived')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.saved_listings (user_id uuid not null references auth.users(id) on delete cascade, listing_id uuid not null references public.listings(id) on delete cascade, created_at timestamptz not null default now(), primary key (user_id, listing_id));
create table if not exists public.inquiries (id uuid primary key default gen_random_uuid(), listing_id uuid not null references public.listings(id) on delete cascade, requester_id uuid not null references auth.users(id) on delete cascade, message text, created_at timestamptz not null default now(), unique (listing_id, requester_id));
alter table public.profiles enable row level security;
alter table public.listings enable row level security;
alter table public.saved_listings enable row level security;
alter table public.inquiries enable row level security;
drop policy if exists "Profiles are publicly readable" on public.profiles;
create policy "Profiles are publicly readable" on public.profiles for select using (true);
drop policy if exists "Users manage their own profile" on public.profiles;
create policy "Users manage their own profile" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists "Active listings are public" on public.listings;
create policy "Active listings are public" on public.listings for select using (status = 'active' or auth.uid() = owner_id);
drop policy if exists "Users create listings" on public.listings;
create policy "Users create listings" on public.listings for insert to authenticated with check (auth.uid() = owner_id);
drop policy if exists "Users update their listings" on public.listings;
create policy "Users update their listings" on public.listings for update to authenticated using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
drop policy if exists "Users delete their listings" on public.listings;
create policy "Users delete their listings" on public.listings for delete to authenticated using (auth.uid() = owner_id);
drop policy if exists "Users manage their saved listings" on public.saved_listings;
create policy "Users manage their saved listings" on public.saved_listings for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users create inquiries" on public.inquiries;
create policy "Users create inquiries" on public.inquiries for insert to authenticated with check (auth.uid() = requester_id);
drop policy if exists "Requesters or owners can read inquiries" on public.inquiries;
create policy "Requesters or owners can read inquiries" on public.inquiries for select to authenticated using (auth.uid() = requester_id or exists (select 1 from public.listings l where l.id = listing_id and l.owner_id = auth.uid()));
insert into storage.buckets (id, name, public) values ('listing-images','listing-images',true) on conflict (id) do nothing;
drop policy if exists "Authenticated users can upload listing images" on storage.objects;
create policy "Authenticated users can upload listing images" on storage.objects for insert to authenticated with check (bucket_id = 'listing-images' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "Public can read listing images" on storage.objects;
create policy "Public can read listing images" on storage.objects for select using (bucket_id = 'listing-images');
drop policy if exists "Users can delete their listing images" on storage.objects;
create policy "Users can delete their listing images" on storage.objects for delete to authenticated using (bucket_id = 'listing-images' and (storage.foldername(name))[1] = auth.uid()::text);